language: node_js
node_js:
  - "8"
script:
  - npm run build
  - >
    printf 
    -------------....:::::::---:---...``````````````````````````````````````````````
    -----------------::-------:/:--...``````````````````````````````````````````````
    --------------:---.......-:/+:-...`````````````````````````.--:::```````````````
    --------:------......```.-:/++:..`````````````````````````-:+++os/``````````````
    --------............``...-:++++:.```````````````````````.:///+oyys-`````````````
    ........................--:+oo++/.````````````````````-:/+++++ossy+`````````````
    ``````...........--------////+////:--...```````````.-//so+oossssoso.````````````
    ......----:::////+/////:://:--:::::::::::::::::::::/+oso+osyyyyyooo.````````````
    :::///++++++++++++////:-------::///////:::::::///ooosyo+oyhmmmhsoso.````````````
    ooooo+++++++//////::----...---::/++/////::::::////oyyso++shmmdyooo+`````````````
    oo+++++++/////:-.....---....--:/++//////::///::::::/osooymNmdy++++-`````````````
    ++++++//////:.......---.....-:/++//::::::::////::::::/+ydmmhso+os+.`````````````
    +++/////:::-.......--:----.-://++/:------://///::::::::/+oso++os++-.````````````
    //:::----......`..:ydmmy/--::////:--------:://///:::::---:/+++osso:-.```````````
    .........`..``  `./ommmm+:---::-::---::oso/:::////::::::---:/+oyyo/:.```````````
    ......```..``  `..+sddh/--------://+shyoyNNms+//::::::::::::://oys+:-.``````````
    ..........``  ``---::-----....--:+sdNy/dNMNNms/:::::-::::::::://o+/:-.``````````
    .........```````.-..........----:/+ohdyddmds/----..---------::://///:.``````````
    ........`````````--:------...---::::::///:-----......---...---:::///:-``````````
    -...---.``````:yhdhhhhhs/-....--------::::::--.......-......----:::::-.`````````
    yo/----.``.```hMNMMMMMNNm+......----.......---.....`........----::::::-.````````
    /o+:---``````-ymNNMMMMMNm/-......--......................------:://:::-.````````
    .------```...:ymNMNNMNNds::--------..................------::::////::::-.```````
    -------````.-+yhmNNNNmhs+/::----:--.............-------------::////://:--.``````
    -------.```.-/shdmmmmddyo+/:::::::::------------------------::////////::-.``````
    -------```....odmNNMNNNmy+///:://+o+/:---:::---------....----:////////::-.``````
    `````..`````..-+ydmmmmNNNmmyhdmmmhy+:::-:----------...------://////////::-.`````
    `````````````..-:oyyyyysshhysssoo+::---:::---------------:::////++++++//::-`````
    ````````````.....-:+////://///::::----:::::-----..------::://////++o++///:-.````
    ```````````.........------::::::::::::::::-----...----::://////++o++++///:-.````
    ``````````........--------::::::::::::::----.--------::::////++ooo+++////::-.```
    ``````````..-.....--------:::::::::::::--..-------:-:::::///++oo+++////:::--.```
    .`````````..-------------::::::::::::::--------::---:--::://+++++/:::::----.````
    .....````.....------------:::::::::::::::/::::::---::-::::///////:::-------.````
    ......````.....----::::::::::///://////////::-:--:::--::::///:-------------.````
    ........```.....-----:///////+++++/////:::--------------::--------...------.````
    ........`````.....---::::///////////::------::-------------.........--------````
    ........`````....----:::::::////::::::-----------::----................---:-.```
    .........````.....-----::::::::::-:---------------------....-..-.....----::-..``
