language: node_js
node_js:
  - "8"
script:
  - npm run build
  - set +x
  - printf -------------....:::::::---:---...``````````````````````````````````````````````
  - printf -----------------::-------:/:--...``````````````````````````````````````````````
  - printf --------------:---.......-:/+:-...`````````````````````````.--:::```````````````
  - printf --------:------......```.-:/++:..`````````````````````````-:+++os/``````````````
  - printf --------............``...-:++++:.```````````````````````.:///+oyys-`````````````
  - printf ........................--:+oo++/.````````````````````-:/+++++ossy+`````````````
  - printf ``````...........--------////+////:--...```````````.-//so+oossssoso.````````````
  - printf ......----:::////+/////:://:--:::::::::::::::::::::/+oso+osyyyyyooo.````````````
  - printf :::///++++++++++++////:-------::///////:::::::///ooosyo+oyhmmmhsoso.````````````
  - printf ooooo+++++++//////::----...---::/++/////::::::////oyyso++shmmdyooo+`````````````
  - printf oo+++++++/////:-.....---....--:/++//////::///::::::/osooymNmdy++++-`````````````
  - printf ++++++//////:.......---.....-:/++//::::::::////::::::/+ydmmhso+os+.`````````````
  - printf +++/////:::-.......--:----.-://++/:------://///::::::::/+oso++os++-.````````````
  - printf //:::----......`..:ydmmy/--::////:--------:://///:::::---:/+++osso:-.```````````
  - printf .........`..``  `./ommmm+:---::-::---::oso/:::////::::::---:/+oyyo/:.```````````
  - printf ......```..``  `..+sddh/--------://+shyoyNNms+//::::::::::::://oys+:-.``````````
  - printf ..........``  ``---::-----....--:+sdNy/dNMNNms/:::::-::::::::://o+/:-.``````````
  - printf .........```````.-..........----:/+ohdyddmds/----..---------::://///:.``````````
  - printf ........`````````--:------...---::::::///:-----......---...---:::///:-``````````
  - printf -...---.``````:yhdhhhhhs/-....--------::::::--.......-......----:::::-.`````````
  - printf yo/----.``.```hMNMMMMMNNm+......----.......---.....`........----::::::-.````````
  - printf /o+:---``````-ymNNMMMMMNm/-......--......................------:://:::-.````````
  - printf .------```...:ymNMNNMNNds::--------..................------::::////::::-.```````
  - printf -------````.-+yhmNNNNmhs+/::----:--.............-------------::////://:--.``````
  - printf -------.```.-/shdmmmmddyo+/:::::::::------------------------::////////::-.``````
  - printf -------```....odmNNMNNNmy+///:://+o+/:---:::---------....----:////////::-.``````
  - printf `````..`````..-+ydmmmmNNNmmyhdmmmhy+:::-:----------...------://////////::-.`````
  - printf `````````````..-:oyyyyysshhysssoo+::---:::---------------:::////++++++//::-`````
  - printf ````````````.....-:+////://///::::----:::::-----..------::://////++o++///:-.````
  - printf ```````````.........------::::::::::::::::-----...----::://////++o++++///:-.````
  - printf ``````````........--------::::::::::::::----.--------::::////++ooo+++////::-.```
  - printf ``````````..-.....--------:::::::::::::--..-------:-:::::///++oo+++////:::--.```
  - printf .`````````..-------------::::::::::::::--------::---:--::://+++++/:::::----.````
  - printf .....````.....------------:::::::::::::::/::::::---::-::::///////:::-------.````
  - printf ......````.....----::::::::::///://////////::-:--:::--::::///:-------------.````
  - printf ........```.....-----:///////+++++/////:::--------------::--------...------.````
  - printf ........`````.....---::::///////////::------::-------------.........--------````
  - printf ........`````....----:::::::////::::::-----------::----................---:-.```
  - printf .........````.....-----::::::::::-:---------------------....-..-.....----::-..``
